### ISSUE TITLE
The getter 'modalBarrierDismissLabel' was called on null

### ISSUE THREAD

**Issue by max02100** [mono0926/adaptive_dialog#10] opened 2020-10-25 12:28 UTC
I use your plugin but on iOS 14 i've this error: 

The following NoSuchMethodError was thrown while handling a gesture:
The getter 'modalBarrierDismissLabel' was called on null.
Receiver: null
Tried calling: modalBarrierDismissLabel

this is my code: 

`return GridView.builder(
      gridDelegate:
          SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 3),
      itemBuilder: (_, index) => Builder(
        builder: (context) => InkWell(
            onTap: () {
              if (index == TeouResponses.MAP_OF_RESPONSES.length - 1) {
                showTextInputDialog(
                        context: context,
                        title: "Je suis...",
                        textFields: [DialogTextField(hintText: "test")],
                        okLabel: "Envoyer",
                        cancelLabel: "Annuler", barrierDismissible: true)
                    .then((inputText) {
                  if (inputText != null && inputText.length > 0) {
                    _textResponse = inputText[0];
                    _actionsAfterCLick(index);
                  }
                });
              } else if (index == TeouResponses.MAP_OF_RESPONSES.length - 2) {
                _onImageButtonPressed(ImageSource.camera,
                    context: context,
                    index: TeouResponses.MAP_OF_RESPONSES.length - 2);
              } else {
                _actionsAfterCLick(index);
              }
            },
            child: Card(
              elevation: 4,
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    SizedBox(
                      height: 60,
                      child: Image(
                          image: TeouResponses.MAP_OF_RESPONSES.values
                              .toList()[index]),
                    ),
                    SizedBox(
                      height: 10,
                    ),
                    Center(
                      child: Text(
                        TeouResponses.MAP_OF_RESPONSES.keys.toList()[index],
                        textAlign: TextAlign.center,
                      ),
                    )
                  ],
                ),
              ),
            )),
      ),
      itemCount: TeouResponses.MAP_OF_RESPONSES.length,
    );`

**Comment by mono0926** [comment] 2020-10-26 03:10
@max02100 

This is the issue for Cupertino-style widgets.
Add note to https://pub.dev/packages/adaptive_dialog#faq by https://github.com/mono0926/adaptive_dialog/commit/ddf8ad5ae5fa490c35feda73208d5966aedc2451.

If the problem is fixed with this change, close the issue please.

**Closed** 2020-12-07 06:13 UTC
